top_srcdir   = /users/alireza/httpd-2.4.46
top_builddir = /users/alireza/httpd-2.4.46
srcdir       = /users/alireza/httpd-2.4.46/os/unix
builddir     = /users/alireza/httpd-2.4.46/os/unix
VPATH        = /users/alireza/httpd-2.4.46/os/unix

LTLIBRARY_NAME    = libos.la
LTLIBRARY_SOURCES = unixd.c

include $(top_srcdir)/build/ltlib.mk
