top_srcdir   = /users/alireza/httpd-2.4.46
top_builddir = /users/alireza/httpd-2.4.46
srcdir       = /users/alireza/httpd-2.4.46/modules/mappers
builddir     = /users/alireza/httpd-2.4.46/modules/mappers
VPATH        = /users/alireza/httpd-2.4.46/modules/mappers

include $(top_srcdir)/build/special.mk

