top_srcdir   = /users/alireza/testing/httpd-ab
top_builddir = /users/alireza/testing/httpd-ab
srcdir       = /users/alireza/testing/httpd-ab/modules/mappers
builddir     = /users/alireza/testing/httpd-ab/modules/mappers
VPATH        = /users/alireza/testing/httpd-ab/modules/mappers

include $(top_srcdir)/build/special.mk

