top_srcdir   = /users/alireza/testing/httpd-ab
top_builddir = /users/alireza/testing/httpd-ab
srcdir       = /users/alireza/testing/httpd-ab/modules/metadata
builddir     = /users/alireza/testing/httpd-ab/modules/metadata
VPATH        = /users/alireza/testing/httpd-ab/modules/metadata

include $(top_srcdir)/build/special.mk

