top_srcdir   = /users/alireza/httpd-2.4.46
top_builddir = /users/alireza/httpd-2.4.46
srcdir       = /users/alireza/httpd-2.4.46/modules/loggers
builddir     = /users/alireza/httpd-2.4.46/modules/loggers
VPATH        = /users/alireza/httpd-2.4.46/modules/loggers

include $(top_srcdir)/build/special.mk

