top_srcdir   = /users/alireza/testing/httpd-ab
top_builddir = /users/alireza/testing/httpd-ab
srcdir       = /users/alireza/testing/httpd-ab/modules/loggers
builddir     = /users/alireza/testing/httpd-ab/modules/loggers
VPATH        = /users/alireza/testing/httpd-ab/modules/loggers

include $(top_srcdir)/build/special.mk

