top_srcdir   = /users/alireza/httpd-2.4.46
top_builddir = /users/alireza/httpd-2.4.46
srcdir       = /users/alireza/httpd-2.4.46/modules/generators
builddir     = /users/alireza/httpd-2.4.46/modules/generators
VPATH        = /users/alireza/httpd-2.4.46/modules/generators

include $(top_srcdir)/build/special.mk

