top_srcdir   = /users/alireza/testing/httpd-ab
top_builddir = /users/alireza/testing/httpd-ab
srcdir       = /users/alireza/testing/httpd-ab/modules/generators
builddir     = /users/alireza/testing/httpd-ab/modules/generators
VPATH        = /users/alireza/testing/httpd-ab/modules/generators

include $(top_srcdir)/build/special.mk

