top_srcdir   = /users/alireza/testing/httpd-ab
top_builddir = /users/alireza/testing/httpd-ab
srcdir       = /users/alireza/testing/httpd-ab/modules/echo
builddir     = /users/alireza/testing/httpd-ab/modules/echo
VPATH        = /users/alireza/testing/httpd-ab/modules/echo

include $(top_srcdir)/build/special.mk

