top_srcdir   = /users/alireza/httpd-2.4.46
top_builddir = /users/alireza/httpd-2.4.46
srcdir       = /users/alireza/httpd-2.4.46/modules/echo
builddir     = /users/alireza/httpd-2.4.46/modules/echo
VPATH        = /users/alireza/httpd-2.4.46/modules/echo

include $(top_srcdir)/build/special.mk

