top_srcdir   = /users/alireza/testing/httpd-ab
top_builddir = /users/alireza/testing/httpd-ab
srcdir       = /users/alireza/testing/httpd-ab/modules/filters
builddir     = /users/alireza/testing/httpd-ab/modules/filters
VPATH        = /users/alireza/testing/httpd-ab/modules/filters

include $(top_srcdir)/build/special.mk

