top_srcdir   = /users/alireza/httpd-2.4.46
top_builddir = /users/alireza/httpd-2.4.46
srcdir       = /users/alireza/httpd-2.4.46/modules/filters
builddir     = /users/alireza/httpd-2.4.46/modules/filters
VPATH        = /users/alireza/httpd-2.4.46/modules/filters

include $(top_srcdir)/build/special.mk

