top_srcdir   = /users/alireza/httpd-2.4.46
top_builddir = /users/alireza/httpd-2.4.46
srcdir       = /users/alireza/httpd-2.4.46/modules/experimental
builddir     = /users/alireza/httpd-2.4.46/modules/experimental
VPATH        = /users/alireza/httpd-2.4.46/modules/experimental
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
