top_srcdir   = /users/alireza/testing/httpd-ab
top_builddir = /users/alireza/testing/httpd-ab
srcdir       = /users/alireza/testing/httpd-ab/modules/aaa
builddir     = /users/alireza/testing/httpd-ab/modules/aaa
VPATH        = /users/alireza/testing/httpd-ab/modules/aaa

include $(top_srcdir)/build/special.mk

