top_srcdir   = /users/alireza/httpd-2.4.46
top_builddir = /users/alireza/httpd-2.4.46
srcdir       = /users/alireza/httpd-2.4.46/modules/aaa
builddir     = /users/alireza/httpd-2.4.46/modules/aaa
VPATH        = /users/alireza/httpd-2.4.46/modules/aaa

include $(top_srcdir)/build/special.mk

