top_srcdir   = /users/alireza/testing/httpd-ab
top_builddir = /users/alireza/testing/httpd-ab
srcdir       = /users/alireza/testing/httpd-ab/server/mpm/event
builddir     = /users/alireza/testing/httpd-ab/server/mpm/event
VPATH        = /users/alireza/testing/httpd-ab/server/mpm/event
include $(top_srcdir)/build/special.mk
