top_srcdir   = /users/alireza/httpd-2.4.46
top_builddir = /users/alireza/httpd-2.4.46
srcdir       = /users/alireza/httpd-2.4.46/server/mpm/event
builddir     = /users/alireza/httpd-2.4.46/server/mpm/event
VPATH        = /users/alireza/httpd-2.4.46/server/mpm/event
include $(top_srcdir)/build/special.mk
