top_srcdir   = /users/alireza/httpd-2.4.46
top_builddir = /users/alireza/httpd-2.4.46
srcdir       = /users/alireza/httpd-2.4.46/modules/cache
builddir     = /users/alireza/httpd-2.4.46/modules/cache
VPATH        = /users/alireza/httpd-2.4.46/modules/cache

include $(top_srcdir)/build/special.mk

