top_srcdir   = /users/alireza/testing/httpd-ab
top_builddir = /users/alireza/testing/httpd-ab
srcdir       = /users/alireza/testing/httpd-ab/modules/cache
builddir     = /users/alireza/testing/httpd-ab/modules/cache
VPATH        = /users/alireza/testing/httpd-ab/modules/cache

include $(top_srcdir)/build/special.mk

