top_srcdir   = /users/alireza/httpd-2.4.46
top_builddir = /users/alireza/httpd-2.4.46
srcdir       = /users/alireza/httpd-2.4.46/os
builddir     = /users/alireza/httpd-2.4.46/os
VPATH        = /users/alireza/httpd-2.4.46/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
