top_srcdir   = /users/alireza/testing/httpd-ab
top_builddir = /users/alireza/testing/httpd-ab
srcdir       = /users/alireza/testing/httpd-ab/os
builddir     = /users/alireza/testing/httpd-ab/os
VPATH        = /users/alireza/testing/httpd-ab/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
