top_srcdir   = /users/alireza/testing/httpd-ab
top_builddir = /users/alireza/testing/httpd-ab
srcdir       = /users/alireza/testing/httpd-ab/srclib
builddir     = /users/alireza/testing/httpd-ab/srclib
VPATH        = /users/alireza/testing/httpd-ab/srclib

BUILD_SUBDIRS = $(AP_BUILD_SRCLIB_DIRS)
CLEAN_SUBDIRS = $(AP_CLEAN_SRCLIB_DIRS)

include $(top_builddir)/build/rules.mk
