top_srcdir   = /users/alireza/testing/httpd-ab
top_builddir = /users/alireza/testing/httpd-ab
srcdir       = /users/alireza/testing/httpd-ab/modules/examples
builddir     = /users/alireza/testing/httpd-ab/modules/examples
VPATH        = /users/alireza/testing/httpd-ab/modules/examples
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
