top_srcdir   = /users/alireza/httpd-2.4.46
top_builddir = /users/alireza/httpd-2.4.46
srcdir       = /users/alireza/httpd-2.4.46/modules/arch/unix
builddir     = /users/alireza/httpd-2.4.46/modules/arch/unix
VPATH        = /users/alireza/httpd-2.4.46/modules/arch/unix

include $(top_srcdir)/build/special.mk

