top_srcdir   = /users/alireza/testing/httpd-ab
top_builddir = /users/alireza/testing/httpd-ab
srcdir       = /users/alireza/testing/httpd-ab/modules/arch/unix
builddir     = /users/alireza/testing/httpd-ab/modules/arch/unix
VPATH        = /users/alireza/testing/httpd-ab/modules/arch/unix

include $(top_srcdir)/build/special.mk

