top_srcdir   = /users/alireza/httpd-2.4.46
top_builddir = /users/alireza/httpd-2.4.46
srcdir       = /users/alireza/httpd-2.4.46/modules/core
builddir     = /users/alireza/httpd-2.4.46/modules/core
VPATH        = /users/alireza/httpd-2.4.46/modules/core

include $(top_srcdir)/build/special.mk

