top_srcdir   = /users/alireza/testing/httpd-ab
top_builddir = /users/alireza/testing/httpd-ab
srcdir       = /users/alireza/testing/httpd-ab/modules/core
builddir     = /users/alireza/testing/httpd-ab/modules/core
VPATH        = /users/alireza/testing/httpd-ab/modules/core

include $(top_srcdir)/build/special.mk

