top_srcdir   = /users/alireza/httpd-2.4.46
top_builddir = /users/alireza/httpd-2.4.46
srcdir       = /users/alireza/httpd-2.4.46/modules/http
builddir     = /users/alireza/httpd-2.4.46/modules/http
VPATH        = /users/alireza/httpd-2.4.46/modules/http

include $(top_srcdir)/build/special.mk

