top_srcdir   = /users/alireza/testing/httpd-ab
top_builddir = /users/alireza/testing/httpd-ab
srcdir       = /users/alireza/testing/httpd-ab/modules/http
builddir     = /users/alireza/testing/httpd-ab/modules/http
VPATH        = /users/alireza/testing/httpd-ab/modules/http

include $(top_srcdir)/build/special.mk

