top_srcdir   = /users/alireza/testing/httpd-ab
top_builddir = /users/alireza/testing/httpd-ab
srcdir       = /users/alireza/testing/httpd-ab/server/mpm
builddir     = /users/alireza/testing/httpd-ab/server/mpm
VPATH        = /users/alireza/testing/httpd-ab/server/mpm

SUBDIRS = $(MPM_SUBDIRS)

include $(top_builddir)/build/rules.mk
