top_srcdir   = /users/alireza/httpd-2.4.46
top_builddir = /users/alireza/httpd-2.4.46
srcdir       = /users/alireza/httpd-2.4.46/server/mpm
builddir     = /users/alireza/httpd-2.4.46/server/mpm
VPATH        = /users/alireza/httpd-2.4.46/server/mpm

SUBDIRS = $(MPM_SUBDIRS)

include $(top_builddir)/build/rules.mk
